config/routes.rb
Rails.application.routes.draw do
  get "tweets/index"
  get "tweets/new"
  get "tweets/create"
  get "tweets/destroy"
  resources :users
  root 'users#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :like_users, through: :likes , source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_many :likes
  has_many :like_tweets, through: :likes , source: :tweet
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path
    else
      render :new
    end
  end


  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to tweets_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    User.create(uid: params[:user][:uid],pass: params[:user][:pass])
    redirect_to root_path
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:uid, :pass, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "L5" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/index.html.erb
<% @users.each do |t| %>
  <p>
    <%= t.uid %> | <%= t.pass %><br>
    <%= link_to '削除', tweet_path(t),  data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
  </p>
<% end %>

<%= link_to '新規登録', new_tweet_path %>

app/views/tweets/new.html.erb
<%= form_with model: @tweet, local: true do |h| %>
  <p>
    <%= h.label :user_id, "ユーザーID" %><br>
    <%= h.number_field :user_id %>
  </p>

  <p>
    <%= h.label :message, "メッセージ" %><br>
    <%= h.text_field :message %>
  </p>

  <%= h.submit "作成" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |u| %>
  <p>
    <%= u.uid %> | <%= u.pass %><br>
    <%= link_to '削除', user_path(u),  data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
  </p>
<% end %>

<%= link_to '新規登録', new_user_path %>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |f| %>
  <%= f.label :uid %>
  <%= f.text_field :uid %>
  <%= f.label :pass %>
  <%= f.password_field :pass %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.submit '登録' %>
<% end %>